import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/redux-povide";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/home/Navbar";
import Foter from "@/components/home/Foter";

const inter = Inter({ subsets: ["latin"] });
export const dynamic = "force-dynamic";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar />
          {children}
          <Foter />
          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
